<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>library</OutputType>
    <Version>1.0.3</Version>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
	  <PackageId>VkKatzi.Net</PackageId>
    <PackageVersion>1.0.3</PackageVersion>
    <Authors>AaronoLW</Authors>
    <Description>C# Bindings for the VkKatzi library</Description>
    <Copyright>Copyright © 2026 AaronoLW</Copyright>
    <RepositoryUrl>https://github.com/KatziIndustries/VkKatzi.Net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
